baseurl = "https://example.org"
title = "Escapolis"
theme = "universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Inici"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Escapes"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Rànquing"
    identifier = "ranquing"
    url  = "/ranquing/"
    weight = 3

[[menu.main]]
    name = "Equip"
    url  = "/equip/"
    weight = 4

[params]
    viewMorePostLink = "/blog/"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "<p>Escapa escapame esca!!</p>"
# copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Twitter"
    url = "https://twitter.com/escapolis"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:info@escapolis.cat"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contacta'ns a twitter or info@escapolis.cat</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """
[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."


